### ISSUE TITLE
Some doubts regarding GSoC Proposal

### ISSUE THREAD

**Issue by ManishAradwad** [ChanchalKumarMaji/Google-Summer-of-Code-2019#1]
Hello @ChanchalKumarMaji , 
I saw that in the previous year you were selected for "Implement Key Research data in TFDS" for GSoC under Tensorflow. Actually, I'm preparing for the same project this year. I just wanted to ask how did you prepare the timeline for the project? What were the steps you mentioned in the proposal?

Thanks a lot for your help!
(And sorry for creating this issue :) I just couldn't find any other way to contact you.)

**Comment by ChanchalKumarMaji** [comment]
Sorry for being late. I just missed this. :disappointed: . 
Yes, mention what u plan to do during the GSoC period. As u can see many datasets have already been added. Try adding some video and audio datasets. 
Mainly in TF, your selection depends on your contributions. So, please mention all your contributions (with PR links) in your proposals. As, u know TF has a dynamic community. The issue u plan to solve during the summer may be solved by someone earlier. So, dont worry about that. The assigned mentors will later change your proposal a bit. 

 :smiley: .
